name: Deploy to EC2

on:
  push:
    branches:
      - docker-code

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build and push Docker image
      run: |
        docker build -t express-docker-image:latest .
        docker tag express-docker-image:latest express-docker-image:latest
    - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push Docker image
        run: docker push express-docker-image:latest

    - name: SSH into EC2 instance and deploy
      uses: subratapurkait/node-express-aws-sdk-S3@docker-code
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.MY_EC2_SSH_KEY }}
        script: |
          sudo docker pull express-docker-image:latest
          sudo docker stop my-node-app || true
          sudo docker rm my-node-app || true
          sudo docker run -d -p 3000:3000 --name my-node-app express-docker-image:latest
